-- MySQL Script generated by MySQL Workbench
-- Mon Jul  8 15:53:35 2019
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema tcc
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema tcc
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `tcc` DEFAULT CHARACTER SET utf8 ;
USE `tcc` ;

-- -----------------------------------------------------
-- Table `tcc`.`clientes`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `tcc`.`clientes` (
  `codigo` INT NOT NULL AUTO_INCREMENT,
  `status` TINYINT NOT NULL DEFAULT 1,
  `login` VARCHAR(45) NOT NULL,
  `senha` VARCHAR(10) NULL,
  `nome` VARCHAR(45) NOT NULL,
  `apelido` VARCHAR(45) NULL,
  `telefone1` VARCHAR(45) NOT NULL,
  `telefone2` VARCHAR(45) NULL,
  `tipo` TINYINT NOT NULL DEFAULT 1,
  `origem` TINYINT NOT NULL DEFAULT 1,
  `cpf` VARCHAR(45) NULL,
  `rg` VARCHAR(45) NULL,
  `cnpj` VARCHAR(45) NULL,
  `ie` VARCHAR(45) NULL,
  `nascimento` DATE NULL,
  `obs` MEDIUMTEXT NULL,
  `endereco` VARCHAR(45) NULL,
  `complemento` VARCHAR(45) NULL,
  `bairro` VARCHAR(45) NULL,
  `cidade` INT NULL,
  `data_cadastro` DATE NOT NULL,
  `data_alteracao` DATE NOT NULL,
  `tipo_acesso` TINYINT NULL,
  `sexo` TINYINT NULL,
  `email` VARCHAR(45) NULL,
  `estado_civil` VARCHAR(45) NULL,
  `profissao` VARCHAR(45) NULL,
  `responsavel` VARCHAR(45) NULL,
  `saldo` FLOAT NULL,
  `foto` MEDIUMBLOB NULL,
  `estado` VARCHAR(45) NULL,
  PRIMARY KEY (`codigo`),
  UNIQUE INDEX `id_clientes_UNIQUE` (`codigo` ASC) VISIBLE,
  UNIQUE INDEX `cpf_UNIQUE` (`cpf` ASC) VISIBLE,
  UNIQUE INDEX `cnpj_UNIQUE` (`cnpj` ASC) VISIBLE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `tcc`.`tipo_produto`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `tcc`.`tipo_produto` (
  `idtipo_produto` INT NOT NULL AUTO_INCREMENT,
  `nome` VARCHAR(45) NULL,
  `descricao` VARCHAR(250) NULL,
  PRIMARY KEY (`idtipo_produto`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `tcc`.`produto`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `tcc`.`produto` (
  `codigo` INT NOT NULL AUTO_INCREMENT,
  `ativo` TINYINT NOT NULL,
  `nome` VARCHAR(45) NOT NULL,
  `estoque` INT NOT NULL,
  `valor_custo` FLOAT NULL,
  `valor_venda` FLOAT NULL,
  `data_entrada` DATE NOT NULL,
  `cod_barras` INT NULL,
  `foto` MEDIUMBLOB NULL,
  `tipo` INT NOT NULL,
  PRIMARY KEY (`codigo`),
  UNIQUE INDEX `idproduto_UNIQUE` (`codigo` ASC) VISIBLE,
  INDEX `fk_produtos_servicos_tipo_produto1_idx` (`tipo` ASC) VISIBLE,
  CONSTRAINT `fk_produtos_servicos_tipo_produto1`
    FOREIGN KEY (`tipo`)
    REFERENCES `tcc`.`tipo_produto` (`idtipo_produto`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `tcc`.`funcionario`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `tcc`.`funcionario` (
  `codigo` INT NOT NULL AUTO_INCREMENT,
  `status` TINYINT NOT NULL DEFAULT 1,
  `login` VARCHAR(45) NOT NULL,
  `senha` VARCHAR(10) NOT NULL,
  `cargo` VARCHAR(45) NOT NULL,
  `nome` VARCHAR(45) NOT NULL,
  `telefone1` VARCHAR(45) NOT NULL,
  `telefone2` VARCHAR(45) NULL,
  `cpf` VARCHAR(45) NULL,
  `rg` VARCHAR(45) NULL,
  `endereco` VARCHAR(45) NULL,
  `complemento` VARCHAR(45) NULL,
  `bairro` VARCHAR(45) NULL,
  `nascimento` DATE NULL,
  `data_criacao` DATE NOT NULL,
  `observacao` TEXT NULL,
  `data_admissao` DATE NULL,
  `data_demissao` DATE NULL,
  `sexo` TINYINT NULL,
  `foto` MEDIUMBLOB NULL,
  `cidade` VARCHAR(45) NULL,
  `estado` VARCHAR(45) NULL,
  PRIMARY KEY (`codigo`),
  UNIQUE INDEX `id_clientes_UNIQUE` (`codigo` ASC) VISIBLE,
  UNIQUE INDEX `cpf_UNIQUE` (`cpf` ASC) VISIBLE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `tcc`.`sistema`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `tcc`.`sistema` (
  `codigo` INT NOT NULL AUTO_INCREMENT,
  `razao` VARCHAR(45) NULL,
  `fantasia` VARCHAR(45) NULL,
  `cnpj` VARCHAR(45) NULL,
  `ie` VARCHAR(45) NULL,
  `endereco` VARCHAR(45) NULL,
  `bairro` VARCHAR(45) NULL,
  `cidade` VARCHAR(45) NULL,
  `uf` VARCHAR(45) NULL,
  `cep` VARCHAR(45) NULL,
  `telefone1` VARCHAR(45) NULL,
  `telefone2` VARCHAR(45) NULL,
  `fax` VARCHAR(45) NULL,
  `email` VARCHAR(45) NULL,
  `site` VARCHAR(45) NULL DEFAULT 0,
  `logo` MEDIUMBLOB NULL,
  PRIMARY KEY (`codigo`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `tcc`.`venda`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `tcc`.`venda` (
  `codigo` INT NOT NULL AUTO_INCREMENT,
  `data_criacao` DATE NOT NULL,
  `data_finalizacao` DATE NOT NULL,
  `fk_cliente` INT NULL,
  `fk_funcionario` INT NULL,
  PRIMARY KEY (`codigo`),
  UNIQUE INDEX `codigo_UNIQUE` (`codigo` ASC) VISIBLE,
  INDEX `fk_funcionario_idx` (`fk_funcionario` ASC) VISIBLE,
  INDEX `fk_cliente_idx` (`fk_cliente` ASC) VISIBLE,
  CONSTRAINT `fk_cliente`
    FOREIGN KEY (`fk_cliente`)
    REFERENCES `tcc`.`clientes` (`codigo`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_funcionario`
    FOREIGN KEY (`fk_funcionario`)
    REFERENCES `tcc`.`funcionario` (`codigo`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `tcc`.`itens_venda`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `tcc`.`itens_venda` (
  `codigo` INT NOT NULL AUTO_INCREMENT,
  `fk_venda` INT NOT NULL,
  `fk_produto` INT NOT NULL,
  `quantidade` FLOAT NOT NULL,
  `valor` FLOAT NOT NULL,
  PRIMARY KEY (`codigo`),
  UNIQUE INDEX `codigo_UNIQUE` (`codigo` ASC) VISIBLE,
  INDEX `fk_venda_idx` (`fk_venda` ASC) VISIBLE,
  INDEX `fk_produto_idx` (`fk_produto` ASC) VISIBLE,
  CONSTRAINT `fk_venda`
    FOREIGN KEY (`fk_venda`)
    REFERENCES `tcc`.`venda` (`codigo`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_produto`
    FOREIGN KEY (`fk_produto`)
    REFERENCES `tcc`.`produto` (`codigo`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `tcc`.`itens_venda_copy1`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `tcc`.`itens_venda_copy1` (
  `codigo` INT NOT NULL AUTO_INCREMENT,
  `fk_venda` INT NOT NULL,
  `fk_produto` INT NOT NULL,
  `quantidade` FLOAT NOT NULL,
  `valor` FLOAT NOT NULL,
  PRIMARY KEY (`codigo`),
  UNIQUE INDEX `codigo_UNIQUE` (`codigo` ASC) VISIBLE,
  INDEX `fk_venda_idx` (`fk_venda` ASC) VISIBLE,
  INDEX `fk_produto_idx` (`fk_produto` ASC) VISIBLE,
  CONSTRAINT `fk_venda0`
    FOREIGN KEY (`fk_venda`)
    REFERENCES `tcc`.`venda` (`codigo`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_produto0`
    FOREIGN KEY (`fk_produto`)
    REFERENCES `tcc`.`produto` (`codigo`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `tcc`.`fornecedor`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `tcc`.`fornecedor` (
  `codigo` INT NOT NULL AUTO_INCREMENT,
  `status` TINYINT NOT NULL DEFAULT 1,
  `nome` VARCHAR(45) NOT NULL,
  `telefone1` VARCHAR(45) NOT NULL,
  `telefone2` VARCHAR(45) NULL,
  `tipo` TINYINT NOT NULL DEFAULT 1,
  `cpf` VARCHAR(45) NULL,
  `rg` VARCHAR(45) NULL,
  `cnpj` VARCHAR(45) NULL,
  `ie` VARCHAR(45) NULL,
  `obs` MEDIUMTEXT NULL,
  `endereco` VARCHAR(45) NULL,
  `complemento` VARCHAR(45) NULL,
  `bairro` VARCHAR(45) NULL,
  `data_cadastro` DATE NOT NULL,
  `data_alteracao` DATE NOT NULL,
  `email` VARCHAR(45) NULL,
  PRIMARY KEY (`codigo`),
  UNIQUE INDEX `id_clientes_UNIQUE` (`codigo` ASC) VISIBLE,
  UNIQUE INDEX `cpf_UNIQUE` (`cpf` ASC) VISIBLE,
  UNIQUE INDEX `cnpj_UNIQUE` (`cnpj` ASC) VISIBLE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `tcc`.`catalogo`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `tcc`.`catalogo` (
  `codigo` INT NOT NULL AUTO_INCREMENT,
  `ativo` TINYINT NOT NULL,
  `nome` VARCHAR(45) NOT NULL,
  `estoque` INT NOT NULL,
  `valor_custo` FLOAT NULL,
  `valor_venda` FLOAT NULL,
  `data_entrada` DATE NOT NULL,
  `cod_barras` INT NULL,
  `foto` MEDIUMBLOB NULL,
  `tipo` INT NOT NULL,
  `fornecedor_codigo` INT NOT NULL,
  PRIMARY KEY (`codigo`),
  UNIQUE INDEX `idproduto_UNIQUE` (`codigo` ASC) VISIBLE,
  UNIQUE INDEX `nome_UNIQUE` (`nome` ASC) VISIBLE,
  INDEX `fk_catalogo_fornecedor1_idx` (`fornecedor_codigo` ASC) VISIBLE,
  CONSTRAINT `fk_catalogo_fornecedor1`
    FOREIGN KEY (`fornecedor_codigo`)
    REFERENCES `tcc`.`fornecedor` (`codigo`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `tcc`.`promotor_vendas`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `tcc`.`promotor_vendas` (
  `codigo` INT NOT NULL AUTO_INCREMENT,
  `status` TINYINT NOT NULL DEFAULT 1,
  `nome` VARCHAR(45) NOT NULL,
  `apelido` VARCHAR(45) NULL,
  `telefone1` VARCHAR(45) NOT NULL,
  `telefone2` VARCHAR(45) NULL,
  `tipo` TINYINT NOT NULL DEFAULT 1,
  `origem` TINYINT NOT NULL DEFAULT 1,
  `cpf` VARCHAR(45) NULL,
  `rg` VARCHAR(45) NULL,
  `cnpj` VARCHAR(45) NULL,
  `ie` VARCHAR(45) NULL,
  `nascimento` DATE NULL,
  `obs` MEDIUMTEXT NULL,
  `endereco` VARCHAR(45) NULL,
  `complemento` VARCHAR(45) NULL,
  `bairro` VARCHAR(45) NULL,
  `data_cadastro` DATE NOT NULL,
  `data_alteracao` DATE NOT NULL,
  `sexo` TINYINT NULL,
  `email` VARCHAR(45) NULL,
  `estado_civil` VARCHAR(45) NULL,
  `foto` MEDIUMBLOB NULL,
  PRIMARY KEY (`codigo`),
  UNIQUE INDEX `id_clientes_UNIQUE` (`codigo` ASC) VISIBLE,
  UNIQUE INDEX `cpf_UNIQUE` (`cpf` ASC) VISIBLE,
  UNIQUE INDEX `cnpj_UNIQUE` (`cnpj` ASC) VISIBLE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `tcc`.`compra`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `tcc`.`compra` (
  `codigo` INT NOT NULL AUTO_INCREMENT,
  `data_criacao` DATE NOT NULL,
  `data_finalizacao` DATE NOT NULL,
  `fk_funcionario` INT NULL,
  `promotor_vendas_codigo` INT NOT NULL,
  PRIMARY KEY (`codigo`),
  UNIQUE INDEX `codigo_UNIQUE` (`codigo` ASC) VISIBLE,
  INDEX `fk_funcionario_idx` (`fk_funcionario` ASC) VISIBLE,
  INDEX `fk_compra_promotor_vendas1_idx` (`promotor_vendas_codigo` ASC) VISIBLE,
  CONSTRAINT `fk_funcionario1`
    FOREIGN KEY (`fk_funcionario`)
    REFERENCES `tcc`.`funcionario` (`codigo`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_compra_promotor_vendas1`
    FOREIGN KEY (`promotor_vendas_codigo`)
    REFERENCES `tcc`.`promotor_vendas` (`codigo`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `tcc`.`itens_compra`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `tcc`.`itens_compra` (
  `codigo` INT NOT NULL AUTO_INCREMENT,
  `fk_venda` INT NOT NULL,
  `fk_produto` INT NOT NULL,
  `quantidade` FLOAT NOT NULL,
  `valor` FLOAT NOT NULL,
  PRIMARY KEY (`codigo`),
  UNIQUE INDEX `codigo_UNIQUE` (`codigo` ASC) VISIBLE,
  INDEX `fk_venda_idx` (`fk_venda` ASC) VISIBLE,
  INDEX `fk_produto_idx` (`fk_produto` ASC) VISIBLE,
  CONSTRAINT `fk_venda1`
    FOREIGN KEY (`fk_venda`)
    REFERENCES `tcc`.`compra` (`codigo`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_produto1`
    FOREIGN KEY (`fk_produto`)
    REFERENCES `tcc`.`catalogo` (`codigo`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `tcc`.`registro`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `tcc`.`registro` (
  `codigo` INT NOT NULL,
  `descricao` VARCHAR(100) NULL,
  PRIMARY KEY (`codigo`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `tcc`.`status_os`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `tcc`.`status_os` (
  `codigo` INT NOT NULL AUTO_INCREMENT,
  `nome` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`codigo`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `tcc`.`ordem_servico`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `tcc`.`ordem_servico` (
  `codigo` INT NOT NULL AUTO_INCREMENT,
  `data_abertura` DATE NOT NULL,
  `data_fechamento` DATE NULL,
  `clientes_codigo` INT NOT NULL,
  `status_codigo` INT NOT NULL,
  `problema_informado` TEXT NULL,
  `diagnostico` TEXT NULL,
  `funcionario_codigo` INT NULL,
  `venda_codigo` INT NOT NULL,
  PRIMARY KEY (`codigo`),
  INDEX `fk_ordem_servico_clientes1_idx` (`clientes_codigo` ASC) VISIBLE,
  INDEX `fk_os_status_idx` (`status_codigo` ASC) VISIBLE,
  INDEX `fk_os_funcionario_idx` (`funcionario_codigo` ASC) VISIBLE,
  INDEX `fk_ordem_servico_venda1_idx` (`venda_codigo` ASC) VISIBLE,
  CONSTRAINT `fk_ordem_servico_clientes1`
    FOREIGN KEY (`clientes_codigo`)
    REFERENCES `tcc`.`clientes` (`codigo`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_os_status`
    FOREIGN KEY (`status_codigo`)
    REFERENCES `tcc`.`status_os` (`codigo`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_os_funcionario`
    FOREIGN KEY (`funcionario_codigo`)
    REFERENCES `tcc`.`funcionario` (`codigo`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_ordem_servico_venda1`
    FOREIGN KEY (`venda_codigo`)
    REFERENCES `tcc`.`venda` (`codigo`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `tcc`.`maquina`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `tcc`.`maquina` (
  `codigo` INT NOT NULL,
  `nome` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`codigo`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `tcc`.`log_acesso_maquinas`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `tcc`.`log_acesso_maquinas` (
  `codigo` INT NOT NULL AUTO_INCREMENT,
  `fk_cliente` INT NOT NULL,
  `fk_maquina` INT NOT NULL,
  `data` DATE NOT NULL,
  `hora_login` TIME NOT NULL,
  `hora_logout` TIME NOT NULL,
  PRIMARY KEY (`codigo`),
  INDEX `fk_cliente_idx` (`fk_cliente` ASC) VISIBLE,
  INDEX `fk_maquina_idx` (`fk_maquina` ASC) VISIBLE,
  CONSTRAINT `fk_cliente`
    FOREIGN KEY (`fk_cliente`)
    REFERENCES `tcc`.`clientes` (`codigo`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_maquina`
    FOREIGN KEY (`fk_maquina`)
    REFERENCES `tcc`.`maquina` (`codigo`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `tcc`.`forma_pagamento`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `tcc`.`forma_pagamento` (
  `codigo` INT NOT NULL AUTO_INCREMENT,
  `nome` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`codigo`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `tcc`.`categoria`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `tcc`.`categoria` (
  `codigo` INT NOT NULL,
  `nome` VARCHAR(45) NULL,
  PRIMARY KEY (`codigo`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `tcc`.`subcategoria`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `tcc`.`subcategoria` (
  `codigo` INT NOT NULL,
  `nome` VARCHAR(45) NULL,
  `categoria_codigo` INT NOT NULL,
  PRIMARY KEY (`codigo`),
  INDEX `fk_subcategoria_categoria1_idx` (`categoria_codigo` ASC) VISIBLE,
  CONSTRAINT `fk_subcategoria_categoria1`
    FOREIGN KEY (`categoria_codigo`)
    REFERENCES `tcc`.`categoria` (`codigo`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `tcc`.`movimento`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `tcc`.`movimento` (
  `codigo` INT UNSIGNED NOT NULL,
  `nome` VARCHAR(45) NULL,
  `valor` FLOAT NOT NULL,
  `data_vencimento` DATE NULL,
  `data_pagamento` DATE NULL,
  `codigo_forma_pagamento` INT NOT NULL,
  `tipo` INT NOT NULL,
  `codigo_categoria` INT NOT NULL,
  `codigo_subcategoria` INT NULL,
  `venda_codigo` INT NULL,
  `compra_codigo` INT NULL,
  PRIMARY KEY (`codigo`),
  INDEX `fk_receber_forma_pagamento_idx` (`codigo_forma_pagamento` ASC) VISIBLE,
  INDEX `fk_caixa_subcategoria_idx` (`codigo_subcategoria` ASC) VISIBLE,
  INDEX `fk_caixa_categoria_idx` (`codigo_categoria` ASC) VISIBLE,
  INDEX `fk_movimento_venda1_idx` (`venda_codigo` ASC) VISIBLE,
  INDEX `fk_movimento_compra1_idx` (`compra_codigo` ASC) VISIBLE,
  CONSTRAINT `fk_movimento_forma_pagamento`
    FOREIGN KEY (`codigo_forma_pagamento`)
    REFERENCES `tcc`.`forma_pagamento` (`codigo`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_movimento_subcategoria`
    FOREIGN KEY (`codigo_subcategoria`)
    REFERENCES `tcc`.`subcategoria` (`codigo`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_movimento_categoria`
    FOREIGN KEY (`codigo_categoria`)
    REFERENCES `tcc`.`categoria` (`codigo`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_movimento_venda1`
    FOREIGN KEY (`venda_codigo`)
    REFERENCES `tcc`.`venda` (`codigo`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_movimento_compra1`
    FOREIGN KEY (`compra_codigo`)
    REFERENCES `tcc`.`compra` (`codigo`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
